### PR TITLE
Added DNT header support

### PR DESCRIPTION
**Pull request by miyurusankalpa**
Added Do Not Track header support for the proxying requests. #23

### CODE REVIEW

**Comment by level420** [comment]
@mattab why is this PR not merged?
We need the DNT header forwarding as well!

**Comment by mattab** [comment]
Thank you for the pull request @miyurusankalpa! :+1: 

Code review/feedback:

* In core here is how we read the DNT header: https://github.com/matomo-org/matomo/blob/3.3.1-b1/plugins/PrivacyManager/DoNotTrackHeaderChecker.php#L115-L118 - it would be good to reuse this same logic in the tracker proxy (and maybe add a comment in both places that if one logic is changed we remember to change the other).
* it would be good to add a new unit test in: https://github.com/matomo-org/tracker-proxy/blob/master/tests/ProxyTest.php that sets the DNT headers (test that both `HTTP_X_DO_NOT_TRACK: 1` and `HTTP_DNT: 1` will forward the do not track header) 

Do you think you'd be able to update the PR?

**Comment by level420** [comment]
@miyurusankalpa do you plan to update this PR soon?

**Comment by diosmosis** [comment]
Closed in https://github.com/matomo-org/tracker-proxy/pull/32, thanks for the PR!

**Pull request closed without merging**
